/*
 *
 * www.jinvovo.com Inc
 * Copyright (c) 2017 All Rights Reserved.
 *
 */
package com.jvv.gateway.dal.entity;

import com.jvv.gateway.facade.constants.enums.GatewayStatusEnum;
import java.util.Date;




/**
 * A data object class directly models database table <tt>telephone_bill_prepaid</tt>.
 * 
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/telephone_bill_prepaid.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 * @author Turalyon
 */
public class TelephoneBillPrepaidDO  extends Entity {
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========
	/**
	 * 订单号
	*/
	protected String orderNo;
	/**
	 * 渠道API
	*/
	protected String channelApi;
	/**
	 * 手机号码
	*/
	protected String phoneNo;
	/**
	 * 交易币种
	*/
	protected String currency;
	/**
	 * 应付额，单位：分
	*/
	protected Long amount;
	/**
	 * 交易状态<br/>
	 * IT:初始<br/>
	 * AS:异步处理<br/>
	 * BP:已报银行<br/>
	 * BS:银行成功<br/>
	 * BF:银行失败<br/>
	 * BE:银行异常(需要对账或查询处理)
	*/
	protected GatewayStatusEnum status;
	/**
	 * 交易日期
	*/
	protected Date transDate;
	/**
	 * 结果编码
	*/
	protected String resultCode;
	/**
	 * 结果信息
	*/
	protected String resultMessage;

	//========== getters and setters ==========
    /**
     * 返回 订单号
     */
	public String getOrderNo() {
		return orderNo;
	}

	/**
	 * 设置 订单号
     */
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
    }
    /**
     * 返回 渠道API
     */
	public String getChannelApi() {
		return channelApi;
	}

	/**
	 * 设置 渠道API
     */
	public void setChannelApi(String channelApi) {
		this.channelApi = channelApi;
    }
    /**
     * 返回 手机号码
     */
	public String getPhoneNo() {
		return phoneNo;
	}

	/**
	 * 设置 手机号码
     */
	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
    }
    /**
     * 返回 交易币种
     */
	public String getCurrency() {
		return currency;
	}

	/**
	 * 设置 交易币种
     */
	public void setCurrency(String currency) {
		this.currency = currency;
    }
    /**
     * 返回 应付额，单位：分
     */
	public Long getAmount() {
		return amount;
	}

	/**
	 * 设置 应付额，单位：分
     */
	public void setAmount(Long amount) {
		this.amount = amount;
    }
    /**
     * 返回 交易状态<br/>
	 * IT:初始<br/>
	 * AS:异步处理<br/>
	 * BP:已报银行<br/>
	 * BS:银行成功<br/>
	 * BF:银行失败<br/>
	 * BE:银行异常(需要对账或查询处理)
     */
	public GatewayStatusEnum getStatus() {
		return status;
	}

	/**
	 * 设置 交易状态<br/>
	 * IT:初始<br/>
	 * AS:异步处理<br/>
	 * BP:已报银行<br/>
	 * BS:银行成功<br/>
	 * BF:银行失败<br/>
	 * BE:银行异常(需要对账或查询处理)
     */
	public void setStatus(GatewayStatusEnum status) {
		this.status = status;
    }
    /**
     * 返回 交易日期
     */
	public Date getTransDate() {
		return transDate;
	}

	/**
	 * 设置 交易日期
     */
	public void setTransDate(Date transDate) {
		this.transDate = transDate;
    }
    /**
     * 返回 结果编码
     */
	public String getResultCode() {
		return resultCode;
	}

	/**
	 * 设置 结果编码
     */
	public void setResultCode(String resultCode) {
		this.resultCode = resultCode;
    }
    /**
     * 返回 结果信息
     */
	public String getResultMessage() {
		return resultMessage;
	}

	/**
	 * 设置 结果信息
     */
	public void setResultMessage(String resultMessage) {
		this.resultMessage = resultMessage;
    }

}
