/*
 *
 * www.jinvovo.com Inc
 * Copyright (c) 2017 All Rights Reserved.
 *
 */
package com.jvv.gateway.dal.entity;

import java.util.Date;




/**
 * A data object class directly models database table <tt>user_message_record_log</tt>.
 * 
 * This file is generated by <tt>iwallet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/user_message_record_log.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>iwallet-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 * @author Turalyon
 */
public class UserMessageRecordLogDO  extends Entity {
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========
	/**
	 * 日志ID
	*/
	protected String logId;
	/**
	 * 发送时间
	*/
	protected Date sendTime;
	/**
	 * 发送内容
	*/
	protected String sendContent;
	/**
	 * 接收短信号码
	*/
	protected String receivePhone;
	/**
	 * 发送短信号码
	*/
	protected String sendPhone;
	/**
	 * 消息类型/用途
	*/
	protected String msgType;
	/**
	 * 是否发送成功  0:失败  1:成功 2:初始状态
	*/
	protected Long isSucess;
	/**
	 * 短信渠道
	*/
	protected String msgChannel;
	/**
	 * 
	*/
	protected String userId;
	/**
	 * 
	*/
	protected Date createtime;
	/**
	 * 
	*/
	protected String resultCode;
	/**
	 * 
	*/
	protected String resultMessage;

	//========== getters and setters ==========
    /**
     * 返回 日志ID
     */
	public String getLogId() {
		return logId;
	}

	/**
	 * 设置 日志ID
     */
	public void setLogId(String logId) {
		this.logId = logId;
    }
    /**
     * 返回 发送时间
     */
	public Date getSendTime() {
		return sendTime;
	}

	/**
	 * 设置 发送时间
     */
	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
    }
    /**
     * 返回 发送内容
     */
	public String getSendContent() {
		return sendContent;
	}

	/**
	 * 设置 发送内容
     */
	public void setSendContent(String sendContent) {
		this.sendContent = sendContent;
    }
    /**
     * 返回 接收短信号码
     */
	public String getReceivePhone() {
		return receivePhone;
	}

	/**
	 * 设置 接收短信号码
     */
	public void setReceivePhone(String receivePhone) {
		this.receivePhone = receivePhone;
    }
    /**
     * 返回 发送短信号码
     */
	public String getSendPhone() {
		return sendPhone;
	}

	/**
	 * 设置 发送短信号码
     */
	public void setSendPhone(String sendPhone) {
		this.sendPhone = sendPhone;
    }
    /**
     * 返回 消息类型/用途
     */
	public String getMsgType() {
		return msgType;
	}

	/**
	 * 设置 消息类型/用途
     */
	public void setMsgType(String msgType) {
		this.msgType = msgType;
    }
    /**
     * 返回 是否发送成功  0:失败  1:成功 2:初始状态
     */
	public Long getIsSucess() {
		return isSucess;
	}

	/**
	 * 设置 是否发送成功  0:失败  1:成功 2:初始状态
     */
	public void setIsSucess(Long isSucess) {
		this.isSucess = isSucess;
    }
    /**
     * 返回 短信渠道
     */
	public String getMsgChannel() {
		return msgChannel;
	}

	/**
	 * 设置 短信渠道
     */
	public void setMsgChannel(String msgChannel) {
		this.msgChannel = msgChannel;
    }
    /**
     * 返回 
     */
	public String getUserId() {
		return userId;
	}

	/**
	 * 设置 
     */
	public void setUserId(String userId) {
		this.userId = userId;
    }
    /**
     * 返回 
     */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * 设置 
     */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
    }
    /**
     * 返回 
     */
	public String getResultCode() {
		return resultCode;
	}

	/**
	 * 设置 
     */
	public void setResultCode(String resultCode) {
		this.resultCode = resultCode;
    }
    /**
     * 返回 
     */
	public String getResultMessage() {
		return resultMessage;
	}

	/**
	 * 设置 
     */
	public void setResultMessage(String resultMessage) {
		this.resultMessage = resultMessage;
    }

}
